version: "3.3"
services:
    mongodb:
        image: mongo
        container_name: mongodb
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ./database:/data/db
        ports:
            - 27017:27017
    zuk:
        container_name: zuk
        build:
            context: ../
            dockerfile: Dockerfile
        image: zuk:latest
        ports:
            - 8081:8081
